#!/usr/bin/env bash

brew update && brew upgrade

brew install git
brew install hub

brew install openssl
brew install jq
brew install gawk
brew install gnu-sed
brew install xz
brew install tmux

brew install ffmpeg
brew install youtube-dl

